version: '3.3'

networks:
  internal:
    external: false

services:
  gc2core:
    image: mapcentia/gc2core
    privileged: true
    networks:
      - internal
      - default
    ports:
      - "8080:80"
    environment:
      - POSTGIS_HOST=postgis
      - POSTGIS_DB=postgres
      - POSTGIS_USER=gc2
      - POSTGIS_PORT=5432
      - POSTGIS_PW=1234
      - POSTGIS_PGBOUNCER=false
  redis:
    image: redis
    networks:
      - internal
#     - default
#   ports:
#     - "6379:6379"
  postgis:
    image: mapcentia/postgis
    volumes:
      - postgis_var_lib_postgresql:/var/lib/postgresql
      - postgis_var_log:/var/log
      - postgis_etc_postgresql:/etc/postgresql
      - postgis_etc_pgbouncer:/etc/pgbouncer
    networks:
      - internal
#     - default
#   ports:
#     - "5432:5432"
    environment:
      - GC2_USER=gc2
      - GC2_PASSWORD=1234
      - GC2_LOCALE=da_DK.UTF-8
  vidi:
    image: mapcentia/vidi
    networks:
      - internal
      - default
    ports:
      - "3000:3000"
    environment:
      - GC2_HOST=http://gc2core

volumes:
  postgis_var_log:
  postgis_etc_postgresql:
  postgis_var_lib_postgresql:
  postgis_etc_pgbouncer:





